apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: frontend-role
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fronted-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: bXktYXBw 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: frontend-role 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-secret-tls
  namespace: {{ .Values.namespace }}
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls