namespace: prod
appName: frontend
port: 80
configmap:
  name: frontend-configmap-v1
image:
  name: frontend
  tag: latest
service:
  name: frontend-svc
ingress:
  name: frontend-ingress
  host:
    name: "api.example.com"
replicas: 2