namespace: prod
appName: frontend
port: 80
configmap:
  name: frontend-configmap-v1
  data:
    CUSTOM_HEADER: 'Test helm!'
image:
  name: frontend
  tag: latest
service:
  name: frontend
ingress:
  name: frontend-ingress
  host:
    name: "api.example.com"