apiVersion: v1               
kind: Service                 
metadata:
  name: docker-service          
spec:
  type: {{ .Values.service.type }}   
  ports:
    - port: {{ .Values.service.port }}  
      targetPort: 3005          
  selector:
    app: docker-deployment           