namespace: dev
appName: backend
port: 80
configmap:
  name: backend-config-map
image:
  name: backend
  tag: latest
service:
  name: backend
ingress:
  name: backend-ingress
  host:
    name: "localhost"