namespace: stage
appName: backend
port: 80
configmap:
  name: backend-config-map
image:
  name: backend
  tag: latest
service:
  name: backend-svc
ingress:
  name: backend-ingress
  host:
    name: "localhost"
replicas: 2