apiVersion: v1
kind: Secret
metadata:
  name: secret-postgres
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  dbname: test-postgres
  username: admin 
  password: psw-test 