apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Value.namespace }}
type: Opaque
data:
  username: VWitYXLw
  password: Pjk1NjghduRnN9xt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Value.namespace }}
  name: backend-role
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: {{ .Value.namespace }}
subjects:
- kind: User
  name: VWitYXLw 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: backend-role 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-migration
  namespace: {{ .Value.namespace }}
type: Opaque
data:
  test.db: ZW52ICJrOHMiIHsKICB1cm
